name: firebase_auth
description: Flutter plugin for Firebase Auth, enabling Android and iOS
  authentication using passwords, phone numbers and identity providers
  like Google, Facebook and Twitter.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth
version: 0.16.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebaseauth
        pluginClass: FirebaseAuthPlugin
      ios:
        pluginClass: FLTFirebaseAuthPlugin
      macos:
        pluginClass: FLTFirebaseAuthPlugin
      web:
        default_package: firebase_auth_web

dependencies:
  meta: ^1.0.4
  firebase_core: ^0.4.4
  firebase_auth_platform_interface:
    path: ../firebase_auth_platform_interface
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # TODO(amirh): Revisit this (either update this part in the  design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  firebase_auth_web:
    path: ../firebase_auth_web

  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0
  async: ^2.3.0
  google_sign_in: ^3.0.4
  firebase_dynamic_links: ^0.3.0
  mockito: ^4.1.1
  uuid: ^2.0.2
  test: ^1.3.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  plugin_platform_interface: ^1.0.2
  e2e: ^0.2.1

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.17.5 <2.0.0"
